export const ADD_TO_CART = '[ORDER] add product to cart'
export const REMOVE_FROM_CART = '[ORDER] remove product from cart'
export const CALCULATE_TOTAL_PRICE = '[ORDER] calculate total cart price'
export const GET_ORDERS = '[ORDER] get all orders'
export const GET_ORDERS_SUCCESS = '[ORDER] get orders success'
export const REMOVE_ORDER_FROM_SERVER = '[ORDER] remove order from server'
export const REMOVE_ORDER_SUCCESS = '[ORDER] remove order from state'
